#!/usr/bin/env python3
"""Validate and render the bounded external-research block on the News page."""

from __future__ import annotations

import argparse
from datetime import date
import json
from pathlib import Path
import re
import sys
from urllib.parse import urlsplit


ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "related-research.json"
NEWS = ROOT / "docs" / "news.md"
START = "<!-- RELATED-RESEARCH:START -->"
END = "<!-- RELATED-RESEARCH:END -->"
ALLOWED_HOSTS = {"arxiv.org", "www.nature.com", "www.kth.se", "doi.org"}
ALLOWED_STATUSES = {"Preprint", "Peer reviewed", "Research news"}


def fail(message: str) -> None:
    print(f"ERROR: {message}", file=sys.stderr)
    raise SystemExit(1)


def words(value: str) -> int:
    return len(re.findall(r"\b[\w’'-]+\b", value))


def load_and_validate() -> dict:
    try:
        payload = json.loads(DATA.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        fail(f"cannot read {DATA.relative_to(ROOT)}: {exc}")

    try:
        reviewed = date.fromisoformat(payload["reviewed_at"])
        items = payload["items"]
    except (KeyError, TypeError, ValueError) as exc:
        fail(f"invalid related-research header: {exc}")

    if reviewed > date.today():
        fail("related-research review date is in the future")
    if not isinstance(items, list) or not 3 <= len(items) <= 4:
        fail("related-research selection must contain three or four items")

    seen: set[str] = set()
    for index, item in enumerate(items, start=1):
        required = {"id", "title", "date", "status", "topic", "summary", "source", "url"}
        if not isinstance(item, dict) or required - item.keys():
            fail(f"related-research item {index} is missing required fields")
        if item["id"].lower() in seen:
            fail(f"duplicate related-research identifier: {item['id']}")
        seen.add(item["id"].lower())
        try:
            published = date.fromisoformat(item["date"])
        except ValueError:
            fail(f"invalid publication date for {item['id']}")
        if published > reviewed:
            fail(f"item is newer than the review date: {item['id']}")
        if (reviewed - published).days > 366:
            fail(f"item is older than one year: {item['id']}")
        if item["status"] not in ALLOWED_STATUSES:
            fail(f"invalid publication status for {item['id']}: {item['status']}")
        if not 18 <= words(item["summary"]) <= 55:
            fail(f"summary for {item['id']} must contain 18–55 words")
        parts = urlsplit(item["url"])
        if parts.scheme != "https" or parts.hostname not in ALLOWED_HOSTS:
            fail(f"unapproved source URL for {item['id']}: {item['url']}")
        combined = " ".join(str(value) for value in item.values()).lower()
        if "sca" + "nia" in combined:
            fail(f"excluded organisation appears in related-research item {item['id']}")
    return payload


def display_date(raw: str) -> str:
    value = date.fromisoformat(raw)
    return f"{value.day} {value.strftime('%B %Y')}"


def render(payload: dict) -> str:
    lines = [
        START,
        "<!-- Generated by scripts/render_related_research.py; edit data/related-research.json. -->",
        f'<p class="review-note"><strong>Last reviewed:</strong> {display_date(payload["reviewed_at"])}.</p>',
        "",
        '<div class="research-grid" markdown>',
        "",
    ]
    for item in payload["items"]:
        lines.extend(
            [
                "<article markdown>",
                f'### {item["title"]}',
                "",
                f'<p class="research-meta">{display_date(item["date"])} · {item["status"]} · {item["topic"]}</p>',
                "",
                item["summary"],
                "",
                f'[Read at {item["source"]}]({item["url"]})',
                "</article>",
                "",
            ]
        )
    lines.extend(["</div>", END])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true", help="update docs/news.md")
    args = parser.parse_args()

    payload = load_and_validate()
    news = NEWS.read_text(encoding="utf-8")
    pattern = re.compile(rf"{re.escape(START)}.*?{re.escape(END)}", re.DOTALL)
    if len(pattern.findall(news)) != 1:
        fail("news page must contain exactly one related-research marker block")
    expected = pattern.sub(render(payload), news)
    if args.write:
        NEWS.write_text(expected, encoding="utf-8")
        print("Rendered related-research block.")
    elif news != expected:
        fail("related-research block is stale; run scripts/render_related_research.py --write")
    else:
        print("Related-research data and rendered block are valid.")


if __name__ == "__main__":
    main()
